---
title: "R Notebook"
output: html_notebook
---

Importar datasets
```{r}
library(nycflights13)

View(flights)
View(airports)
View(planes)
View(airlines)
View(weather)

```

<!-- 1. INNER JOIN -->
```{r}
#1.1
flights %>%
    inner_join(planes, by="tailnum")

#1.2
flights %>%
  inner_join(airlines, by="carrier")

#1.3
flights %>%
  inner_join(airports, by=c("origin" = "faa")) %>%
  inner_join(airports, by=c("dest" = "faa"))

#1.4
flights %>%
  inner_join(weather, by=c("year", "month", "day", "hour", "origin"))
```
<!-- 2. DATS MANIPULATION -->
```{r}
#2.1
flights %>%
  count(year, month, day) %>%
  filter(n>1000) %>%
  arrange(desc(n))

#2.2
flights_selected <- flights %>%
  select(year:day, hour, origin, dest, tailnum, carrier, arr_delay, dep_delay)

#2.3
airlines %>%
  left_join(flights_selected) %>%
  select (-origin, -dest) %>%
  mutate (tot_delay=arr_delay+dep_delay)

```
```{r}
#2.4
precip_delay <- flights %>%
  left_join(weather, by=c("year", "month", "day", "hour", "origin")) %>%
  group_by(precip) %>%
  summarise(delay=mean(dep_delay), na.rm=TRUE) %>%
  replace_na(list(delay=0))

precip_delay

```
```{r}
#2.5
library(ggplot2)

ggplot(precip_delay, aes(x=precip, y=delay)) +
  geom_point()

```
```{r}
#2.6
flight_airports <- flights %>%
  filter(year == 2013) %>%
  filter(month == 5) %>%
  filter(day == 10) %>%
  group_by(dest) %>%
  summarise(delay=mean(arr_delay), na.arm=TRUE) %>%
  inner_join(airports, by=c("dest" = "faa"))

#2.7
ggplot(flight_airports, aes(x=lon, y=lat, color=delay, size=delay)) +
  geom_point()


```
```{r}
#2.8
flights %>%
  inner_join(planes, suffix=c("_flights", "_planes")) %>%
  transmute (tailnum, manufacturer, pi=(dep_delay/arr_delay)/air_time)

```


